version: "3.9" # optional since v1.27.0
services:
  api:
    build: .
    image: node:alpine
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
      - ./node_modules:/app/node_modules
      - ./postgres_data/:/var/lib/postgresql/data/
    command: >
      sh -c "yarn seed:run --env production &&
      yarn start"
    links:
      - database
    depends_on:
      - database
  database:
    image: 'postgres:latest'
    container_name: postgres_koa_container
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: strapi
        POSTGRES_HOST: postgres_koa_container